hard_totals = [None,
               None,
               None,
               None,
               None,
               [None, None, 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'hit', 'double', 'double', 'double', 'double', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit', 'hit'],
               [None, None, 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit'],
               [None, None, 'hit', 'hit', 'stand', 'stand', 'stand', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'stand', 'stand', 'stand', 'stand', 'stand', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'stand', 'stand', 'stand', 'stand', 'stand', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'stand', 'stand', 'stand', 'stand', 'stand', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'stand', 'stand', 'stand', 'stand', 'stand', 'hit', 'hit', 'hit', 'hit', 'hit']]

soft_totals = [None,
               None,
               [None, None, 'hit', 'hit', 'hit', 'double', 'double', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'hit', 'hit', 'hit', 'double', 'double', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'hit', 'hit', 'double', 'double', 'double', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'hit', 'hit', 'double', 'double', 'double', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'hit', 'double', 'double', 'double', 'double', 'hit', 'hit', 'hit', 'hit', 'hit'],
               [None, None, 'stand', 'double', 'double', 'double', 'double', 'stand', 'stand', 'hit', 'hit', 'hit']]

pairs = [None,
         None,
         [None, None, 'split', 'split', 'split', 'split', 'split', 'split', 'hit', 'hit', 'hit', 'hit'],
         [None, None, 'split', 'split', 'split', 'split', 'split', 'split', 'hit', 'hit', 'hit', 'hit'],
         [None, None, 'hit', 'hit', 'hit', 'split', 'split', 'hit', 'hit', 'hit', 'hit', 'hit'],
         [None, None, 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'hit', 'hit'],
         [None, None, 'split', 'split', 'split', 'split', 'split', 'hit', 'hit', 'hit', 'hit', 'hit'],
         [None, None, 'split', 'split', 'split', 'split', 'split', 'split', 'hit', 'hit', 'hit', 'hit'],
         [None, None, 'split', 'split', 'split', 'split', 'split', 'split', 'split', 'split', 'split', 'split'],
         [None, None, 'split', 'split', 'split', 'split', 'split', 'split', 'stand', 'stand', 'split', 'stand'],
         [None, None, 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand', 'stand'],
         [None, None, 'split', 'split', 'split', 'split', 'split', 'split', 'split', 'split', 'split', 'split']]
